From 5e07b19aa34f01063924f8ee7269af13d95d3bed Mon Sep 17 00:00:00 2001
From: Joseph Sutton <josephsutton@catalyst.net.nz>
Date: Wed, 27 Oct 2021 19:18:20 +1300
Subject: [PATCH 316/361] CVE-2020-25722 pytest: Raise an error when adding a
 dynamic test that would overwrite an existing test

BUG: https://bugzilla.samba.org/show_bug.cgi?id=14753

Signed-off-by: Joseph Sutton <josephsutton@catalyst.net.nz>
Reviewed-by: Andrew Bartlett <abartlet@samba.org>
---
 python/samba/tests/__init__.py | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/python/samba/tests/__init__.py b/python/samba/tests/__init__.py
index e04ddcb4ba8..ffb8e58f471 100644
--- a/python/samba/tests/__init__.py
+++ b/python/samba/tests/__init__.py
@@ -102,7 +102,10 @@ class TestCase(unittest.TestCase):
         def fn(self):
             getattr(self, "_%s_with_args" % fnname)(*args)
         fn.__doc__ = doc
-        setattr(cls, "%s_%s" % (fnname, suffix), fn)
+        attr = "%s_%s" % (fnname, suffix)
+        if hasattr(cls, attr):
+            raise RuntimeError(f"Dynamic test {attr} already exists!")
+        setattr(cls, attr, fn)
 
     @classmethod
     def setUpDynamicTestCases(cls):
-- 
2.30.2

